export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const RESET_START = 'Reset_START'
export const RESET_SUCCESS = 'Reset_SUCCESS'
export const RESET_FAIL = 'Reset_FAIL'



export const PRODUCT_START = 'PRODUCT_START'
export const PRODUCT_LIST = 'PRODUCT_LIST'
export const PRODUCT_DELETE = 'PRODUCT_DELETE'
export const PRODUCT_DELETESTATUS = 'PRODUCT_DELETESTATUS'

export const PRODUCT_ADD = 'PRODUCT_ADD'
export const PRODUCT_SAVE = 'PRODUCT_SAVE'
export const PRODUCT_EDITSTART = 'PRODUCT_EDITSTART'
export const PRODUCT_EDITGET = 'PRODUCT_EDITGET'



export const CATEGORY_START = 'CATEGORY_START'
export const CATEGORY_LIST = 'CATEGORY_LIST'
export const CATEGORY_DELETE = 'CATEGORY_DELETE'
export const CATEGORY_DELETESTATUS = 'CATEGORY_DELETESTATUS'

export const CATEGORY_ADD = 'CATEGORY_ADD'
export const CATEGORY_SAVE = 'CATEGORY_SAVE'
export const CATEGORY_EDITSTART = 'CATEGORY_EDITSTART'
export const CATEGORY_EDITGET = 'CATEGORY_EDITGET'



export const ORDER_START = 'ORDER_START'
export const ORDER_LIST = 'ORDER_LIST'
export const ORDER_DELETE = 'ORDER_DELETE'
export const ORDER_DELETESTATUS = 'ORDER_DELETESTATUS'

export const ORDER_ADD = 'ORDER_ADD'
export const ORDER_SAVE = 'ORDER_SAVE'
export const ORDER_EDITSTART = 'ORDER_EDITSTART'
export const ORDER_EDITGET = 'ORDER_EDITGET'



export const ADMIN_START = 'ADMIN_START'
export const ADMIN_LIST = 'ADMIN_LIST'
export const ADMIN_ADD = 'ADMIN_ADD'
export const ADMIN_SAVE = 'ADMIN_SAVE'

export const ADMIN_EDITSTART = 'ADMIN_EDITSTART'
export const ADMIN_EDITGET = 'ADMIN_EDITGET'



export const USER_START = 'USER_START'
export const USER_LIST = 'USER_LIST'
export const USER_DELETE = 'USER_DELETE'
export const USER_DELETESTATUS = 'USER_DELETESTATUS'

export const USER_ADD = 'USER_ADD'
export const USER_SAVE = 'USER_SAVE'
export const USER_EDITSTART = 'USER_EDITSTART'
export const USER_EDITGET = 'USER_EDITGET'